package com.appsters.simpleGames.games.sudoku.model

object Quotes {
    val list = listOf(
        "The only way to do great work is to love what you do. - Steve Jobs",
        "Life is what happens when you're busy making other plans. - John Lennon",
        "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
        "It does not matter how slowly you go as long as you do not stop. - Confucius",
        "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
        "The purpose of our lives is to be happy. - Dalai Lama",
        "Get busy living or get busy dying. - Stephen King",
        "You only live once, but if you do it right, once is enough. - Mae West",
        "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas A. Edison",
        "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
        "Never let the fear of striking out keep you from playing the game. - Babe Ruth",
        "Money and success don’t change people; they merely amplify what is already there. - Will Smith",
        "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
        "Not how long, but how well you have lived is the main thing. - Seneca",
        "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
        "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it. - Henry Ford",
        "In order to write about life first you must live it. - Ernest Hemingway",
        "The big lesson in life, baby, is never be scared of anyone or anything. - Frank Sinatra",
        "Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth. - (Attributed to various sources)",
        "Curiosity about life in all of its aspects, I think, is still the secret of great creative people. - Leo Burnett",
        "Life is not a problem to be solved, but a reality to be experienced. - Soren Kierkegaard",
        "The unexamined life is not worth living. - Socrates",
        "Turn your wounds into wisdom. - Oprah Winfrey",
        "The way I see it, if you want the rainbow, you gotta put up with the rain. - Dolly Parton",
        "Do all the good you can, for all the people you can, in all the ways you can, as long as you ever can. - Hillary Clinton",
        "Don’t settle for what life gives you; make life better and build something. - Ashton Kutcher",
        "Everything negative – pressure, challenges – is all an opportunity for me to rise. - Kobe Bryant",
        "I like criticism. It makes you strong. - LeBron James",
        "You never really learn much from hearing yourself speak. - George Clooney",
        "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this. - Celine Dion",
        "Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty. - John F. Kennedy",
        "Live for each second without hesitation. - Elton John",
        "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
        "Life is really simple, but we insist on making it complicated. - Confucius",
        "Life is a succession of lessons which must be lived to be understood. - Ralph Waldo Emerson",
        "My mama always said, life is like a box of chocolates. You never know what you're gonna get. - Forrest Gump",
        "Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits. Watch your habits; they become character. Watch your character; it becomes your destiny. - Lao-Tzu",
        "When we do the best that we can, we never know what miracle is wrought in our life or the life of another. - Helen Keller",
        "The healthiest response to life is joy. - Deepak Chopra",
        "Life is like a coin. You can spend it any way you wish, but you only spend it once. - Lillian Dickson",
        "The best portion of a good man's life is his little, nameless, unremembered acts of kindness and of love. - Wordsworth",
        "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
        "Life is ten percent what happens to you and ninety percent how you respond to it. - Charles Swindoll",
        "Keep smiling, because life is a beautiful thing and there's so much to smile about. - Marilyn Monroe",
        "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship. - Buddha",
        "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. - Dr. Seuss",
        "Good friends, good books, and a sleepy conscience: this is the ideal life. - Mark Twain",
        "Life would be tragic if it weren't funny. - Stephen Hawking",
        "Live in the sunshine, swim the sea, drink the wild air. - Ralph Waldo Emerson",
        "The greatest pleasure of life is love. - Euripides",
        "Life is what we make it, always has been, always will be. - Grandma Moses",
        "Life's tragedy is that we get old too soon and wise too late. - Benjamin Franklin",
        "Life is about making an impact, not making an income. - Kevin Kruse",
        "I have missed more than 9000 shots in my career. I have lost almost 300 games. 26 times I have been trusted to take the game winning shot and missed. I have failed over and over and over again in my life. And that is why I succeed. - Michael Jordan",
        "Every strike brings me closer to the next home run. - Babe Ruth",
        "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
        "Life shrinks or expands in proportion to one's courage. - Anais Nin",
        "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down ‘happy’. They told me I didn’t understand the assignment, and I told them they didn’t understand life. - John Lennon",
        "Too many of us are not living our dreams because we are living our fears. - Les Brown",
        "I believe every human has a finite number of heartbeats. I don't intend to waste any of mine. - Neil Armstrong",
        "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
        "If you live long enough, you'll make mistakes. But if you learn from them, you'll be a better person. - Bill Clinton",
        "Life is short, and it is up to you to make it sweet. - Sarah Louise Delany",
        "The longer I live, the more beautiful life becomes. - Frank Lloyd Wright",
        "Every moment is a fresh beginning. - T.S. Eliot",
        "When you cease to dream you cease to live. - Malcolm Forbes",
        "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine. - Morris West",
        "Don't cry because it's over, smile because it happened. - Dr. Seuss",
        "If you can do what you do best and be happy, you're further along in life than most people. - Leonardo DiCaprio",
        "We should remember that just as a positive outlook on life can promote good health, so can everyday acts of kindness. - Hillary Clinton",
        "Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve. - Mary Kay Ash",
        "It is our choices that show what we truly are, far more than our abilities. - J.K. Rowling",
        "If you're not stubborn, you'll give up on experiments too soon. And if you're not flexible, you'll pound your head against the wall and you won't see a different solution to a problem you're trying to solve. - Jeff Bezos",
        "The best way to predict your future is to create it. - Abraham Lincoln",
        "You must be the change you wish to see in the world. - Mahatma Gandhi",
        "Luck is what happens when preparation meets opportunity. - Seneca",
        "A journey of a thousand miles begins with a single step. - Lao Tzu",
        "Dream big and dare to fail. - Norman Vaughan",
        "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
        "It always seems impossible until it's done. - Nelson Mandela",
        "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
        "Act as if what you do makes a difference. It does. - William James",
        "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
        "Believe you can and you're halfway there. - Theodore Roosevelt",
        "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
        "Move out of your comfort zone. You can only grow if you are willing to feel awkward and uncomfortable when you try something new. - Brian Tracy",
        "It is never too late to be what you might have been. - George Eliot",
        "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
        "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
        "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
        "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
        "The best revenge is massive success. - Frank Sinatra",
        "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
        "Go confidently in the direction of your dreams! Live the life you've imagined. - Henry David Thoreau",
        "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
        "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
        "If you tell the truth, you don't have to remember anything. - Mark Twain",
        "A friend is someone who knows all about you and still loves you. - Elbert Hubbard",
        "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde"
    )
}
